#!/usr/bin/env python3
"""
JobDB Auto Application Script (Playwright)
- Credentials are entered locally and never sent to any external service.
- Preview + manual confirmation required before every application.
- Requires jobdb_report.md generated by CrewAI first.
"""

import asyncio
import json
import re
import sys
from pathlib import Path
from getpass import getpass
from datetime import datetime

from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout


# ── Configuration ────────────────────────────────────────────────────────────
JOBDB_BASE_URL = "https://www.jobdb.com/hk"
JOBDB_LOGIN_URL = "https://www.jobdb.com/hk/en/jobseeker/login"
REPORT_FILE = "jobdb_report.md"

MAX_APPLICATIONS = 10
HEADLESS = False                    # Set to True for fully automated runs
CV_FILE = Path("your_CV.docx")

# Cover Letter Template
COVER_LETTER_TEMPLATE = """
Your COVER LETTER TEPLATE
""".strip()


# ── Parse Recommended Jobs from CrewAI Report ───────────────────────────────
def parse_recommended_jobs(report_path: str) -> list[dict]:
    """Parse recommended jobs from the CrewAI Markdown report."""
    path = Path(report_path)
    if not path.exists():
        print(f"⚠️  Report file not found: {report_path}")
        print("   Running in manual search mode.\n")
        return []

    content = path.read_text(encoding="utf-8")
    jobs = []

    # Improved regex to match report format
    pattern = re.compile(
        r"###\s*\d+\.\s*(.+?)\s*—\s*(.+?)\n"
        r".*?申請連結[:：]\s*(https?://\S+)",
        re.DOTALL | re.IGNORECASE
    )

    for match in pattern.finditer(content):
        jobs.append({
            "title": match.group(1).strip(),
            "company": match.group(2).strip(),
            "apply_url": match.group(3).strip(),
        })

    print(f"✅ Loaded {len(jobs)} recommended jobs from report.")
    return jobs


# ── Confirmation Prompt ─────────────────────────────────────────────────────
def confirm_application(job: dict, index: int, total: int) -> bool:
    """Ask user for confirmation before applying."""
    print(f"\n{'─' * 60}")
    print(f" [{index}/{total}]  APPLICATION PREVIEW")
    print(f" Position : {job['title']}")
    print(f" Company  : {job['company']}")
    print(f" URL      : {job.get('apply_url', 'N/A')}")
    print(f"{'─' * 60}")

    while True:
        ans = input(" Proceed with application? [y/N/q] > ").strip().lower()
        if ans in ["y", "yes"]:
            return True
        if ans in ["n", "no"]:
            return False
        if ans == "q":
            print("🛑 Operation cancelled by user.")
            sys.exit(0)


# ── Main Application Logic ──────────────────────────────────────────────────
async def main():
    print("=" * 65)
    print("🚀 JobDB Automatic Application Script")
    print(f"   Started : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 65)

    # ── Login Credentials (Local only) ─────────────────────────────────────
    print("\n🔑 Please enter your JobDB credentials (stored only in memory)")
    email = input(" Email    : ").strip()
    password = getpass(" Password : ")

    # Load jobs from report
    jobs = parse_recommended_jobs(REPORT_FILE)

    applied = []
    skipped = []
    failed = []

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=HEADLESS, slow_mo=700)
        context = await browser.new_context(
            viewport={"width": 1366, "height": 900},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
        )
        page = await context.new_page()

        # ── Login ───────────────────────────────────────────────────────────
        print("\n🔐 Logging into JobDB...")
        await page.goto(JOBDB_LOGIN_URL, wait_until="domcontentloaded")

        try:
            await page.fill('input[type="email"], input[name*="email"]', email)
            await page.fill('input[type="password"], input[name*="password"]', password)
            await page.click('button[type="submit"], input[type="submit"]')

            await page.wait_for_url(re.compile(r"dashboard|jobseeker|home"), timeout=15000)
            print("✅ Login successful")
        except PlaywrightTimeout:
            print("❌ Login timeout. Please complete login manually in the browser.")
            input("Press Enter after you have logged in...")

        # ── If no jobs from report, perform basic search ─────────────────────
        if not jobs:
            print("\n🔍 No report found. Searching for Security Engineer jobs...")
            search_url = f"{JOBDB_BASE_URL}/en/job-search?q=security+engineer&l=Hong+Kong"
            await page.goto(search_url, wait_until="domcontentloaded")
            await page.wait_for_timeout(3000)

            # Extract job links (basic fallback)
            links = await page.query_selector_all('a[href*="/hk/en/job/"], a[href*="/job/"]')
            for link in links[:MAX_APPLICATIONS]:
                href = await link.get_attribute("href")
                title = (await link.inner_text()).strip()[:80]
                if href:
                    full_url = href if href.startswith("http") else JOBDB_BASE_URL + href
                    jobs.append({
                        "title": title or "Your Jon Title",
                        "company": "Unknown",
                        "apply_url": full_url,
                    })

        # ── Apply Loop ──────────────────────────────────────────────────────
        total = min(len(jobs), MAX_APPLICATIONS)
        print(f"\n📋 Starting application process for up to {total} positions...\n")

        for i, job in enumerate(jobs[:total], 1):
            if not confirm_application(job, i, total):
                skipped.append(job["title"])
                continue

            try:
                await page.goto(job["apply_url"], wait_until="domcontentloaded")
                await page.wait_for_timeout(2500)

                # Click Apply button
                apply_button = await page.query_selector(
                    'a:has-text("Apply Now"), button:has-text("Apply"), '
                    'button:has-text("Quick Apply"), a:has-text("Easy Apply")'
                )

                if apply_button:
                    await apply_button.click()
                    await page.wait_for_timeout(2000)
                else:
                    print("   ⚠️  Could not find Apply button. Skipping...")
                    failed.append(job["title"])
                    continue

                # Fill Cover Letter
                cover_field = await page.query_selector('textarea')
                if cover_field:
                    cover_text = COVER_LETTER_TEMPLATE.format(
                        job_title=job["title"],
                        company=job["company"]
                    )
                    await cover_field.fill(cover_text)
                    print("   ✍️  Cover letter filled")

                # Upload CV
                if CV_FILE.exists():
                    file_input = await page.query_selector('input[type="file"]')
                    if file_input:
                        await file_input.set_input_files(str(CV_FILE))
                        print("   📎 CV uploaded")

                # Final submission
                print("   ⏳ Please review the application in browser...")
                await page.wait_for_timeout(4000)

                submit_btn = await page.query_selector(
                    'button:has-text("Submit"), button:has-text("Send"), '
                    'input[type="submit"]:has-text("Apply")'
                )

                if submit_btn:
                    await submit_btn.click()
                    print(f"✅ Application submitted: {job['title']}")
                    applied.append(job["title"])
                else:
                    print("   ⚠️  Submit button not found. Please submit manually.")
                    input("   Press Enter after submitting...")
                    applied.append(job["title"] + " (manual)")

            except Exception as e:
                print(f"❌ Error applying to {job['title']}: {e}")
                failed.append(job["title"])

            await page.wait_for_timeout(1500)

        await browser.close()

    # ── Summary ─────────────────────────────────────────────────────────────
    print(f"\n{'=' * 65}")
    print("🎯 APPLICATION SUMMARY")
    print(f"{'=' * 65}")
    print(f"✅ Successfully Applied : {len(applied)}")
    for job in applied:
        print(f"   • {job}")

    if skipped:
        print(f"\n⏭️  Skipped : {len(skipped)}")
    if failed:
        print(f"\n❌ Failed : {len(failed)}")

    # Save log
    log_data = {
        "date": datetime.now().isoformat(),
        "applied": applied,
        "skipped": skipped,
        "failed": failed,
        "total_attempted": len(jobs)
    }

    Path("apply_log.json").write_text(
        json.dumps(log_data, ensure_ascii=False, indent=2)
    )
    print(f"\n📄 Application log saved to: apply_log.json")


if __name__ == "__main__":
    asyncio.run(main())
